// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AxxsssssClient is the client API for Axxsssss service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AxxsssssClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type axxsssssClient struct {
	cc grpc.ClientConnInterface
}

func NewAxxsssssClient(cc grpc.ClientConnInterface) AxxsssssClient {
	return &axxsssssClient{cc}
}

func (c *axxsssssClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxxxx.xxxss.Axxsssss/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AxxsssssServer is the server API for Axxsssss service.
// All implementations must embed UnimplementedAxxsssssServer
// for forward compatibility
type AxxsssssServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAxxsssssServer()
}

// UnimplementedAxxsssssServer must be embedded to have forward compatible implementations.
type UnimplementedAxxsssssServer struct {
}

func (UnimplementedAxxsssssServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAxxsssssServer) mustEmbedUnimplementedAxxsssssServer() {}

// UnsafeAxxsssssServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AxxsssssServer will
// result in compilation errors.
type UnsafeAxxsssssServer interface {
	mustEmbedUnimplementedAxxsssssServer()
}

func RegisterAxxsssssServer(s grpc.ServiceRegistrar, srv AxxsssssServer) {
	s.RegisterService(&Axxsssss_ServiceDesc, srv)
}

func _Axxsssss_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxxsssssServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxxxx.xxxss.Axxsssss/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxxsssssServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Axxsssss_ServiceDesc is the grpc.ServiceDesc for Axxsssss service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Axxsssss_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxxxx.xxxss.Axxsssss",
	HandlerType: (*AxxsssssServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Axxsssss_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Axxsssss.proto",
}
