// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XXXXXXXClient is the client API for XXXXXXX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XXXXXXXClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type xXXXXXXClient struct {
	cc grpc.ClientConnInterface
}

func NewXXXXXXXClient(cc grpc.ClientConnInterface) XXXXXXXClient {
	return &xXXXXXXClient{cc}
}

func (c *xXXXXXXClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxx.GGGAAA.XXXXXXX/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXXXXXXServer is the server API for XXXXXXX service.
// All implementations must embed UnimplementedXXXXXXXServer
// for forward compatibility
type XXXXXXXServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedXXXXXXXServer()
}

// UnimplementedXXXXXXXServer must be embedded to have forward compatible implementations.
type UnimplementedXXXXXXXServer struct {
}

func (UnimplementedXXXXXXXServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedXXXXXXXServer) mustEmbedUnimplementedXXXXXXXServer() {}

// UnsafeXXXXXXXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XXXXXXXServer will
// result in compilation errors.
type UnsafeXXXXXXXServer interface {
	mustEmbedUnimplementedXXXXXXXServer()
}

func RegisterXXXXXXXServer(s grpc.ServiceRegistrar, srv XXXXXXXServer) {
	s.RegisterService(&XXXXXXX_ServiceDesc, srv)
}

func _XXXXXXX_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXXXXXServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxx.GGGAAA.XXXXXXX/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXXXXXServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XXXXXXX_ServiceDesc is the grpc.ServiceDesc for XXXXXXX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XXXXXXX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxx.GGGAAA.XXXXXXX",
	HandlerType: (*XXXXXXXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _XXXXXXX_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXXXXXX.proto",
}
