// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XXXXXXClient is the client API for XXXXXX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XXXXXXClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type xXXXXXClient struct {
	cc grpc.ClientConnInterface
}

func NewXXXXXXClient(cc grpc.ClientConnInterface) XXXXXXClient {
	return &xXXXXXClient{cc}
}

func (c *xXXXXXClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/XXXXX.TTXXAA.XXXXXX/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXXXXXServer is the server API for XXXXXX service.
// All implementations must embed UnimplementedXXXXXXServer
// for forward compatibility
type XXXXXXServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedXXXXXXServer()
}

// UnimplementedXXXXXXServer must be embedded to have forward compatible implementations.
type UnimplementedXXXXXXServer struct {
}

func (UnimplementedXXXXXXServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedXXXXXXServer) mustEmbedUnimplementedXXXXXXServer() {}

// UnsafeXXXXXXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XXXXXXServer will
// result in compilation errors.
type UnsafeXXXXXXServer interface {
	mustEmbedUnimplementedXXXXXXServer()
}

func RegisterXXXXXXServer(s grpc.ServiceRegistrar, srv XXXXXXServer) {
	s.RegisterService(&XXXXXX_ServiceDesc, srv)
}

func _XXXXXX_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXXXXServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XXXXX.TTXXAA.XXXXXX/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXXXXServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XXXXXX_ServiceDesc is the grpc.ServiceDesc for XXXXXX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XXXXXX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "XXXXX.TTXXAA.XXXXXX",
	HandlerType: (*XXXXXXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _XXXXXX_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXXXXX.proto",
}
